"""FastAPI server — routes and startup.

Three routes:
    GET /              → HTML page (auto-plays briefing, activates Vapi Q&A)
    GET /briefing.mp3  → MP3 audio bytes from server_state
    POST /vapi/webhook → Receives Vapi Q&A turns, returns answer text

Run with:
    uvicorn agentlens.server.main:app --host 0.0.0.0 --port 7432
"""

from __future__ import annotations

import os

from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse, Response

from agentlens.server.state import server_state
from agentlens.server.voice import handle_vapi_webhook

app = FastAPI(title="AgentLens Voice Server")


# ── HTML page ─────────────────────────────────────────────────────────────────

# VAPI_PUBLIC_KEY and VAPI_ASSISTANT_ID come from environment variables.
# The public key is safe to embed in the browser — it only allows starting
# calls, not administrative operations (those require the private key).

_HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>AgentLens — Eval Briefing</title>
  <style>
    body {{
      font-family: monospace;
      background: #0f0f0f;
      color: #e0e0e0;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: 100vh;
      margin: 0;
    }}
    h1 {{ font-size: 1.2rem; color: #888; }}
    #status {{ margin-top: 1rem; color: #aaa; font-size: 0.9rem; }}
  </style>
</head>
<body>
  <h1>AgentLens</h1>
  <p id="status">Playing briefing...</p>

  <!-- The briefing audio. autoplay starts it immediately on page load. -->
  <audio id="briefing" src="/briefing.mp3" autoplay></audio>

  <!-- Vapi web SDK loaded from their CDN -->
  <script src="https://cdn.vapi.ai/web-sdk.js"></script>

  <script>
    const vapiPublicKey   = "{vapi_public_key}";
    const vapiAssistantId = "{vapi_assistant_id}";

    const briefingAudio = document.getElementById("briefing");
    const statusEl      = document.getElementById("status");

    // When the briefing finishes, activate Vapi for Q&A
    briefingAudio.addEventListener("ended", () => {{
      statusEl.textContent = "Listening for your questions...";

      // Vapi() takes your public key — safe to use in the browser
      const vapi = new Vapi(vapiPublicKey);

      // start() takes the assistant ID you created in the Vapi dashboard
      vapi.start(vapiAssistantId);

      // Update status on Vapi events
      vapi.on("speech-start", () => {{
        statusEl.textContent = "Speaking...";
      }});
      vapi.on("speech-end", () => {{
        statusEl.textContent = "Listening...";
      }});
      vapi.on("error", (e) => {{
        statusEl.textContent = "Error: " + e.message;
      }});
    }});

    // Handle autoplay being blocked by the browser
    // (browsers block autoplay until the user interacts with the page)
    briefingAudio.addEventListener("error", () => {{
      statusEl.textContent = "Click anywhere to play the briefing.";
      document.body.addEventListener("click", () => {{
        briefingAudio.play();
        statusEl.textContent = "Playing briefing...";
      }}, {{ once: true }});
    }});
  </script>
</body>
</html>"""


@app.get("/", response_class=HTMLResponse)
def index() -> HTMLResponse:
    """Serve the browser page that plays the briefing and handles Q&A.

    VAPI_PUBLIC_KEY and VAPI_ASSISTANT_ID must be set as environment variables.
    The public key is embedded in the HTML — this is safe, it is designed to
    be used in client-side code.
    """
    html = _HTML_TEMPLATE.format(
        vapi_public_key=os.environ.get("VAPI_PUBLIC_KEY", ""),
        vapi_assistant_id=os.environ.get("VAPI_ASSISTANT_ID", ""),
    )
    return HTMLResponse(content=html)


# ── Audio endpoint ────────────────────────────────────────────────────────────

@app.get("/briefing.mp3")
def get_briefing_audio() -> Response:
    """Serve the MP3 audio bytes generated by ElevenLabs.

    The audio is stored in server_state.audio_bytes after run_briefing() is called.
    Returns an empty 200 response if no audio has been generated yet — the browser
    will log an audio decode error, which is caught by the error handler in the HTML.
    """
    return Response(
        content=server_state.audio_bytes,
        media_type="audio/mpeg",
    )


# ── Vapi webhook ──────────────────────────────────────────────────────────────

@app.post("/vapi/webhook")
async def vapi_webhook(request: Request) -> dict:
    """Receive a Q&A turn from Vapi and return the answer.

    Vapi calls this endpoint every time the user finishes speaking a question.
    The endpoint calls Claude with the question + eval context and returns
    answer text. Vapi converts the text to speech and plays it to the user.

    The route is async because Vapi can time out if the response takes too long
    (> 5 seconds). Using async allows FastAPI to handle other requests while
    waiting for the LLM response.
    """
    return await handle_vapi_webhook(request)


# ── Health check ──────────────────────────────────────────────────────────────

@app.get("/health")
def health() -> dict:
    """K8s liveness probe endpoint.

    Returns 200 as long as the server is running.
    K8s uses this to decide whether to restart the pod.
    """
    return {"status": "ok"}
